<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Đăng nhập vào hệ thống</title>
    <link rel="stylesheet" href="../_/style.css">
    <link rel="stylesheet" href="../_/bootstrap.min.css">
    <script src="../_/jquery-1.11.2.min.js"></script>
    <script src="../_/TweenLite.min.js"></script>
    <script src="../_/script.js"></script>
</head>
<body>
    <div class="container">
        <div class="row vertical-offset-100">
            <div class="col-md-4 col-md-offset-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Đăng nhập vào hệ thống</h3>
                    </div>
                    <div class="panel-body">
                        <form method="post" action="login.php">
                            <fieldset>
                                <div class="form-group">
                                    <input class="form-control" placeholder="Tên đăng nhập" name="username" type="text">
                                </div>
                                <div class="form-group">
                                    <input class="form-control" placeholder="Mật khẩu" name="password" type="password" value="">
                                </div>
                                <input class="btn btn-lg btn-success btn-block" name="login" type="submit" value="Đăng nhập">
                            </fieldset>
                        </form>
                        <?php if(isset($is_error)){?>
                            <div class="alert alert-danger" role="alert"><?php echo $is_error;?></div>
                        <?php };?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>